### ISSUE TITLE
Support k3s distribution

### ISSUE THREAD

**Issue by saurabh3460** [iptables-viz/iptables-viz#12]
Tested it on k3s cluster since k3s runs as binary containing all core component as single process so I get this issue.
https://github.com/k3s-io/k3s#how-is-this-lightweight-or-smaller-than-upstream-kubernetes

`2023/04/16 18:12:08 No kube-proxy pods found`

@neelanjan00 @26tanishabanik please drop suggestion on this.

**Comment by saurabh3460** [comment]
seems like need to find a way that it run this iptable command inside the process

https://github.com/iptables-viz/iptables-viz/blob/b17fafcb2d012c349fa07817b8bba66b085c57e0/backend/utility/utility.go#L60

**Comment by 26tanishabanik** [comment]
@saurabh3460 , I did some digging on `k3s` by installing it on `ubuntu`, there is no such `kube-proxy` pod in the `kube-system` namespace. There is only one pod in that namespace, which is a service loadbalancer and had the `iptables` command installed in it, but it doesn't show any kubernetes ip rules. And, I don't think it is possible to run the `iptables` command from inside the `k3s` binary which is already pre-built.

**Comment by saurabh3460** [comment]
make sense, will do some search, for now I will close this issue.

Thanks
